baseurl = "http://www.gentoo-cn.info"
languageCode = "zh-cn"
title = "Gentoo Linux 中文资讯"
canonifyurls = true
copyright = "&copy; 2014 - 2015 <a href=\"http://gentoo-cn.info/\">Gentoo Linux 中文资讯</a>。除非特别注明，本站所有原创文章皆采用 <a href=\"http://www.creativecommons.org/licenses/by/3.0/cn/\">“署名 3.0中国大陆”</a> 的创作共用协议。"
disqusShortname = "gentoo-cn-info"

[permalinks]
pages = "/:filename/"
article = "/article/:filename/"

[params]
description = "“编译我世界”"

[indexes]
tag = "tags"
article = "articles"